name: chatanything
channels:
  - menpo
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.8.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==2.0.1+cu117 
    - torchvision==0.15.2+cu117
    - torchaudio==2.0.2
    - librosa 
    - gfpgan
    - facexlib==0.3.0
    - face_alignment==1.3.5
    - yacs==0.1.8
    - numba
    - openai-whisper
    - kornia
    - diffusers
    - transformers
    - dlib
    - huggingface-hub
    - pydantic==1.10.9
    - langchain==0.0.310
    - gradio==3.41.0
    - gradio-client==0.5.0
    - omegaconf
    - openai
    - opencv-python
    - imageio-ffmpeg
    # for voice-changer
    - moviepy
    - edge-tts
    - fairseq
    - praat-parselmouth
    - pyworld
    - faiss-cpu
    - accelerate
    - ffmpeg
    - ffmpeg-python